<a href="https://colab.research.google.com/github/farhanns481/python-assessment/blob/main/numpy%26pandas_ass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a NumPy array with values from 10 to 49 (inclusive).


In [1]:
import numpy as np
x=np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [2]:
x1=np.reshape(x,(4,10))
x1

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [3]:
x1[3:4]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

2. Create two 3×3 matrices:

In [4]:
x=np.full((3,3),5)
x

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [5]:
y=np.arange(1,10).reshape(3,3)
display(y)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
z=np.add(x,y)
z

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [8]:
v = np.multiply(x,y)
v

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [9]:
v1=np.transpose(v)
v1

array([[ 5, 20, 35],
       [10, 25, 40],
       [15, 30, 45]])

3. Create a NumPy array of 15 random integers between 10 and 100

In [10]:
E=np.random.randint(10,100,size=15)
E

array([61, 94, 79, 11, 57, 41, 88, 47, 39, 38, 84, 54, 10, 93, 64])

In [11]:
updated=np.where(E>51,-1,E)
updated

array([-1, -1, -1, 11, -1, 41, -1, 47, 39, 38, -1, -1, 10, -1, -1])

In [12]:
np.sum(updated==-1)

np.int64(9)

4. Generate a 5×4 array with random values between 0 and 1 (float)

In [14]:
x=np.random.random((5,4))
x

array([[0.7668562 , 0.24776178, 0.17618501, 0.34327677],
       [0.88496312, 0.79941498, 0.22518412, 0.10714103],
       [0.43440657, 0.85487875, 0.92668582, 0.8255621 ],
       [0.94925078, 0.41938925, 0.22462458, 0.66999421],
       [0.95249288, 0.78338714, 0.79298721, 0.55550745]])

In [13]:
row_sum=np.sum(x,axis=1)
np.argmax(row_sum)

np.int64(0)

In [15]:
min_row=np.min(x,axis=1,keepdims=True)
max_row=np.max(x,axis=1,keepdims=True)
normalized=(x-min_row)/(max_row-min_row)
normalized

array([[1.        , 0.12117871, 0.        , 0.28288456],
       [1.        , 0.8900158 , 0.15176105, 0.        ],
       [0.        , 0.85413346, 1.        , 0.79458059],
       [1.        , 0.2687795 , 0.        , 0.61461983],
       [1.        , 0.57402534, 0.59820776, 0.        ]])

5. arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])

In [16]:
arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
unique_elements,counts=np.unique(arr,return_counts=True)
print(unique_elements)
print(counts)

[1 3 5 7 9]
[2 2 3 1 1]


In [17]:
duplicate_elements=unique_elements[counts > 1]
duplicate_elements

array([1, 3, 5])

6. Create a 6×6 NumPy array with values from 1 to 36.


In [18]:
x=np.arange(1,37).reshape(6,6)
x

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [19]:
middle=x[1:5,1:5]
middle

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17],
       [20, 21, 22, 23],
       [26, 27, 28, 29]])

In [20]:
even=middle[middle%2==0]
even

array([ 8, 10, 14, 16, 20, 22, 26, 28])

In [21]:
even.reshape(2,4)

array([[ 8, 10, 14, 16],
       [20, 22, 26, 28]])

7. Generate an array of shape (3, 4) with values from 0 to 11.

In [22]:
p=np.arange(0,12).reshape(3,4)
p

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
p.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [24]:
p.reshape(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
p.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

8 . Create an array: a = np.array([[1, 2], [3, 4]])


In [26]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [27]:
new = np.array([[5, 6]])
new_row = np.append(a, new, axis=0)
new_row

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
newc = np.array([7, 8, 9]).reshape(3, 1)
new_col = np.append(new_row, newc, axis=1)
display(new_col)

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

9.a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

In [29]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
d=np.concatenate([a,b,c])
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
d_reshape=d.reshape((3,3))
d_reshape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
d_diagonal=np.diag(d_reshape)
d_diagonal

array([1, 5, 9])

10. Create a NumPy array of integers from 1 to 20

In [36]:
x=np.arange(1,20)

In [39]:
y=x[(x%3==0)| (x%5==0)]
y

array([ 3,  5,  6,  9, 10, 12, 15, 18])

In [38]:
y.size

8

In [42]:
import pandas as pd
import numpy as np

import seaborn as sns

1. Load the Titanic dataset and display the first 10 rows.

In [41]:
data=sns.load_dataset("titanic")

In [43]:
data.head(10)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
6    man        True    E  Southampton    no   True  
7  child       False  NaN  Southampton    no  False  
8  woman       False  NaN  Southampton   yes  False  
9  child       False  NaN    Cherbourg   yes  False

2. Find the number of missing values in each column.


In [44]:
data.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

3. Find the percentage of passengers who survived, grouped by gender.

In [45]:
percentage=data.groupby("sex")["survived"].mean()*100
percentage.round(2)

sex
female    74.20
male      18.89
Name: survived, dtype: float64

4. Find the average, median, and standard deviation of passenger ages.


In [47]:
age=data['age']
avr=age.mean()
med=age.median()
std_age=age.std()
print(avr)
print(med)
print(std_age)

29.69911764705882
28.0
14.526497332334044


5. Count how many passengers were in each class (pclass).


In [48]:
pclass=data['pclass']
pclass.value_counts()

pclass
3    491
1    216
2    184
Name: count, dtype: int64

6. Show all passengers who were female, under age 18, and survived.

In [49]:
survived_female = data[(data['sex'] == 'female') & (data['age'] < 18) & (data['survived'] == 1)]
display(survived_female)

survived  pclass     sex    age  sibsp  parch      fare embarked   class  \
9           1       2  female  14.00      1      0   30.0708        C  Second   
10          1       3  female   4.00      1      1   16.7000        S   Third   
22          1       3  female  15.00      0      0    8.0292        Q   Third   
39          1       3  female  14.00      1      0   11.2417        C   Third   
43          1       2  female   3.00      1      2   41.5792        C  Second   
58          1       2  female   5.00      1      2   27.7500        S  Second   
68          1       3  female  17.00      4      2    7.9250        S   Third   
84          1       2  female  17.00      0      0   10.5000        S  Second   
156         1       3  female  16.00      0      0    7.7333        Q   Third   
172         1       3  female   1.00      1      1   11.1333        S   Third   
184         1       3  female   4.00      0      2   22.0250        S   Third   
208         1       3  female  16.00      0      0    7.7500        Q   Third   
233         1       3  female   5.00      4      2   31.3875        S   Third   
237         1       2  female   8.00      0      2   26.2500        S  Second   
307         1       1  female  17.00      1      0  108.9000        C   First   
329         1       1  female  16.00      0      1   57.9792        C   First   
381         1       3  female   1.00      0      2   15.7417        C   Third   
389         1       2  female  17.00      0      0   12.0000        C  Second   
435         1       1  female  14.00      1      2  120.0000        S   First   
446         1       2  female  13.00      0      1   19.5000        S  Second   
448         1       3  female   5.00      2      1   19.2583        C   Third   
469         1       3  female   0.75      2      1   19.2583        C   Third   
479         1       3  female   2.00      0      1   12.2875        S   Third   
504         1       1  female  16.00      0      0   86.5000        S   First   
530         1       2  female   2.00      1      1   26.0000        S  Second   
535         1       2  female   7.00      0      2   26.2500        S  Second   
618         1       2  female   4.00      2      1   39.0000        S  Second   
644         1       3  female   0.75      2      1   19.2583        C   Third   
689         1       1  female  15.00      0      1  211.3375        S   First   
691         1       3  female   4.00      0      1   13.4167        C   Third   
720         1       2  female   6.00      0      1   33.0000        S  Second   
750         1       2  female   4.00      1      1   23.0000        S  Second   
777         1       3  female   5.00      0      0   12.4750        S   Third   
780         1       3  female  13.00      0      0    7.2292        C   Third   
781         1       1  female  17.00      1      0   57.0000        S   First   
830         1       3  female  15.00      1      0   14.4542        C   Third   
853         1       1  female  16.00      0      1   39.4000        S   First   
875         1       3  female  15.00      0      0    7.2250        C   Third   

       who  adult_male deck  embark_town alive  alone  
9    child       False  NaN    Cherbourg   yes  False  
10   child       False    G  Southampton   yes  False  
22   child       False  NaN   Queenstown   yes   True  
39   child       False  NaN    Cherbourg   yes  False  
43   child       False  NaN    Cherbourg   yes  False  
58   child       False  NaN  Southampton   yes  False  
68   woman       False  NaN  Southampton   yes  False  
84   woman       False  NaN  Southampton   yes   True  
156  woman       False  NaN   Queenstown   yes   True  
172  child       False  NaN  Southampton   yes  False  
184  child       False  NaN  Southampton   yes  False  
208  woman       False  NaN   Queenstown   yes   True  
233  child       False  NaN  Southampton   yes  False  
237  child       False  NaN  Southampton   yes  False  
307  

7. Replace missing age values with the median age.


In [51]:
age.fillna(med,inplace=True)
age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

8. Create a column age_group with values:


In [52]:
conditions = [data['age'] < 18, (data['age'] >= 18) & (data['age'] < 60), data['age']>60]
values = ['Child','Adult', 'Senior']
data['age_group'] = np.select(conditions, values, default='Unknown')
data.head(10)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male  28.0      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone age_group  
0    man        True  NaN  Southampton    no  False     Adult  
1  woman       False    C    Cherbourg   yes  False     Adult  
2  woman       False  NaN  Southampton   yes   True     Adult  
3  woman       False    C  Southampton   yes  False     Adult  
4    man        True  NaN  Southampton    no   True     Adult  
5    man        True  NaN   Queenstown    no   True     Adult  
6    man        True    E  Southampton    no   True     Adult  
7  child       False  NaN  Southampton    no  False     Child  
8  woman       False  NaN  Southampton   yes  False     Adult  
9  child       False  NaN    Cherbourg   yes  False     Child

9. Display the top 5 passengers who paid the highest fare

In [53]:
data = data.sort_values("fare",ascending=False)
data.head()

survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
679         1       1    male  36.0      0      1  512.3292        C  First   
258         1       1  female  35.0      0      0  512.3292        C  First   
737         1       1    male  35.0      0      0  512.3292        C  First   
88          1       1  female  23.0      3      2  263.0000        S  First   
438         0       1    male  64.0      1      4  263.0000        S  First   

       who  adult_male deck  embark_town alive  alone age_group  
679    man        True    B    Cherbourg   yes  False     Adult  
258  woman       False  NaN    Cherbourg   yes   True     Adult  
737    man        True    B    Cherbourg   yes   True     Adult  
88   woman       False    C  Southampton   yes  False     Adult  
438    man        True    C  Southampton    no  False    Senior

10. Find the average fare paid, grouped by both pclass and sex

In [54]:
data.groupby(['pclass','sex'])["fare"].mean()

pclass  sex   
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: fare, dtype: float64

11. Rename the following columns:

In [55]:
data.rename(columns={ 'sex' :'gender','fare' : 'ticket_fare'},inplace=True)
data.head()

survived  pclass  gender   age  sibsp  parch  ticket_fare embarked  \
679         1       1    male  36.0      0      1     512.3292        C   
258         1       1  female  35.0      0      0     512.3292        C   
737         1       1    male  35.0      0      0     512.3292        C   
88          1       1  female  23.0      3      2     263.0000        S   
438         0       1    male  64.0      1      4     263.0000        S   

     class    who  adult_male deck  embark_town alive  alone age_group  
679  First    man        True    B    Cherbourg   yes  False     Adult  
258  First  woman       False  NaN    Cherbourg   yes   True     Adult  
737  First    man        True    B    Cherbourg   yes   True     Adult  
88   First  woman       False    C  Southampton   yes  False     Adult  
438  First    man        True    C  Southampton    no  False    Senior

12. Count the number of passengers who survived and didn’t survive, grouped by class

In [56]:
survived_by_class = data.groupby(['class', 'survived']).size()
display(survived_by_class)

/tmp/ipython-input-1151376387.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  survived_by_class = data.groupby(['class', 'survived']).size()


class   survived
First   0            80
        1           136
Second  0            97
        1            87
Third   0           372
        1           119
dtype: int64

13. Find the average age of passengers grouped by both class and gender

In [57]:
average_age =data.groupby(["class","gender"])["age"].mean()
display(average_age)

/tmp/ipython-input-1719243699.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  average_age =data.groupby(["class","gender"])["age"].mean()


class   gender
First   female    33.978723
        male      38.995246
Second  female    28.703947
        male      30.512315
Third   female    23.572917
        male      26.911873
Name: age, dtype: float64